name: ExtDN M2 Copy Paste Detector
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpmd:
    name: M2 Copy Paste Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-copy-paste-detector@master
