name: ExtDN M2 PHPStan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan@master
        with:
          composer_name: foo/magento2-foobar
